version: "3.9"

services:
  # -------------------------------
  # Temporal Worker container
  # -------------------------------
  workflow_worker_pattern1:
    build:
      context: ./wf_worker_pattern1
      dockerfile: Dockerfile
    container_name: wf-worker-pattern1
    environment:
      - TEMPORAL_HOST=host.docker.internal:7233
      - POSTGRES_CONNECTION_STRING=postgresql://postgres.sceeibvfwcdhooljytsq:Zsupabase~1@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
      - TASK_QUEUE=default-task-queue
    networks:
      - temporal-network

  # -------------------------------
  # FastAPI API container
  # -------------------------------
  workflow_mgt_api:
    build:
      context: ./wf_mgt_api
      dockerfile: Dockerfile
    container_name: wf-mgt-api
    environment:
      - TEMPORAL_HOST=host.docker.internal:7233
      - TASK_QUEUE=default-task-queue
    ports:
      - "8000:8000"
    depends_on:
      - workflow_worker_pattern1
    networks:
      - temporal-network

# -------------------------------
# Network
# -------------------------------
networks:
  temporal-network:
    driver: bridge